export const SkillData = [
  { id: 1, skill: "Git" },
  { id: 2, skill: "Javascript" },
  { id: 3, skill: "Typescript" },
  { id: 4, skill: "Python" },
  { id: 5, skill: "React.js" },
  { id: 6, skill: "Next.js" },
  { id: 7, skill: "Svelte" },
  { id: 8, skill: "Tailwindcss" },
  { id: 9, skill: "Node.js" },
  { id: 10, skill: "Express.js" },
  { id: 11, skill: "MongoDB" },
  { id: 12, skill: "PostgresSQL" },
  { id: 13, skill: "Firebase" },
  { id: 14, skill: "GraphQL" },
  { id: 15, skill: "Jest" },
  { id: 16, skill: "Mocha" },
  { id: 17, skill: "Postman" },
  { id: 18, skill: "Thunder Client" },
];
